#!/usr/bin/python3
# -*- coding: utf-8 -*-

__author__ = 'fi11222'

import os
from ec_local_param import *

class EcAppParam:
    """
    Static class containing all the global parameters which do not depend on the environment (dev/qualif/prod).
    """

    # transfer of local params from LocalParam to EcAppParam
    gcm_prodEnv = LocalParam.gcm_prodEnv
    gcm_appDomain = LocalParam.gcm_appDomain
    gcm_httpPort = LocalParam.gcm_httpPort
    gcm_dbServer = LocalParam.gcm_dbServer
    gcm_dbUserLocal = LocalParam.gcm_dbUserLocal
    gcm_dbPasswordLocal = LocalParam.gcm_dbPasswordLocal
    gcm_debugModeOn = LocalParam.gcm_debugModeOn
    gcm_verboseModeOn = LocalParam.gcm_verboseModeOn
    gcm_skipBrowscap = LocalParam.gcm_skipBrowscap
    gcm_mailSender = LocalParam.gcm_mailSender
    gcm_smtpServer = LocalParam.gcm_smtpServer
    gcm_amazonSmtp = LocalParam.gcm_amazonSmtp
    gcm_sesIamUser = LocalParam.gcm_sesIamUser
    gcm_sesUserName = LocalParam.gcm_sesUserName
    gcm_sesPassword = LocalParam.gcm_sesPassword
    gcm_appRoot = LocalParam.gcm_appRoot
    gcm_gmailSmtp = LocalParam.gcm_gmailSmtp
    gcm_mailSenderPassword = LocalParam.gcm_mailSenderPassword

    #: Static files root (copied from :any:`LocalParam`)
    gcm_staticRoot = LocalParam.gcm_appRoot

    # general parameters
    #: Application name (used in many contexts like logger names, cookie name, etc)
    gcm_appName = 'ScripTrans'
    #: Application version (dev version with three figures)
    gcm_appVersion = '0.0.0'
    #: App description (used in title of HTML pages ...)
    gcm_appTitle = 'Scripture Translation Engine'

    # HTTP server parameters

    #: Cookie lifetime in days (100 years)
    gcm_cookiePersistence = 365*100

    #: Cookie name for the terminal ID
    gcm_sessionName = 'ECTerminalID_{0}'.format(gcm_appName)

    # Database parameters
    #: Database name
    gcm_dbDatabase = 'ScripTrans'
    #: Database username (copied from :any:`LocalParam`)
    gcm_dbUser = gcm_dbUserLocal
    #: Database password (copied from :any:`LocalParam`)
    gcm_dbPassword = gcm_dbPasswordLocal

    #: Min size of DB connection pool
    gcm_connectionPoolMinCount = 30
    #: Max size of DB connection pool
    gcm_connectionPoolMaxCount = 50

    #: Flag to disable the connection pool feature. If `True` then new connection creation on each request
    gcm_noConnectionPool = True

    #: average db connection life span (in hours)
    gcm_dbcLifeAverage = 2

    # Logging
    #: Recipients of e-mail messages generated by the logging system
    gcm_mailRecipients = ['nicolas.reimen@gmail.com', 'nrtmp@free.fr']
    #: Location of CSV log file
    gcm_logFile = os.path.join(gcm_appRoot, 'Log/ec_log.csv')

    # Templates
    #: Template of the browser test page
    gcm_templateBrowserTest = os.path.join(gcm_appRoot, 'Templates/browser_test.html')
    #: Template of the 'Wrong browser' page
    gcm_templateBadBrowser = os.path.join(gcm_appRoot, 'Templates/bad_browser.html')

    # Browscap
    gcm_browscapUrl = 'http://browscap.org/stream?q=BrowsCapCSV'
    gcm_browscapLatestVersionUrl = 'http://browscap.org/version-number'
    gcm_browscapLocalFile = os.path.join(gcm_appRoot, 'browscap_latest.csv')

    # Multi Language
    @classmethod
    def i18n(cls, k):
        """
        Access to the internationalization table.
        :param k: key to the message string. Must be of the form `xx-kkkkkk`, where `xx` is a two letter language code
        :return: the requested message string.
        """
        return cls.gcm_userStrings[k]

    # The internationalization table
    gcm_userStrings = {
        'en-TestingBrowserMsg': """
            The application is testing the capabilities of your browser ...
        """,
        'fr-TestingBrowserMsg': """
            L'application teste les caractéristiques de votre navigateur ...
        """,
        'en-GainAccess1Msg': """
            If you are not redirected within 30 seconds, please enable JavaScript and Cookies then click on
        """,
        'fr-GainAccess1Msg': """
            Si vous n'êtes pas redirigé dans les 30 secondes, merci d'activer JavaScript et les cookies puis cliquer
        """
    }

